all:
	g++ -o a.out main.cpp -DTEST -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-missing-field-initializers -Wno-deprecated-declarations -O2 -fsanitize=address --std=c++11
clean:
	rm -f ./a.out
