all:
	g++ -o a.out main.cpp -DTEST -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-missing-field-initializers -Wno-deprecated-declarations -O2  --std=c++17 -ggdb #-fsanitize=address
clean:
	rm -f ./a.out
